### ISSUE TITLE
Back-button doesn't work when viewing application

### ISSUE THREAD

**Issue by wschoot** [openshift-mobile/openshift-mobile#56] opened 2014-03-06 08:38 UTC
Hi,

Whenever I select "View Application", there's no way the back-button on my phone will take me back to the applications overview. Viewing the app itself works fine.

Wouter

**Comment by sabre1041** [comment] 2014-03-06 12:41
Issue has been verified and appears to be due to a flaw in the PhoneGap plugin system. Application viewing leverages the [InAppBrowser](https://cordova.apache.org/docs/en/3.0.0/cordova_inappbrowser_inappbrowser.md.html) plugin and on certain versions of PhoneGap, the process of building the application fails to add the plugin completely and silently errors. Verified on PhoneGap 3.1 and resolved using PhoneGap 3.4.

<u>Steps to diagnose:</u>
- Remove contents of plugin directory
- Execute `phonegap local plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git`
  - Any result other than `[phonegap] successfully added the plugin` indicates affected PhoneGap version

<u>Resolution:</u>
- Upgrade PhoneGap
  - `npm install -g phonegap'
- Upgrade Android Platform (Optional)
  - PhoneGap 3.4 requires Android platform version >= 19
- Remove contents of the following directories
  - platforms
  - plugins
- Build project

Please try to resolve using the steps above and verify solution

**Comment by wschoot** [comment] 2014-03-06 13:37
Hi,

Thanks for the extensive writeup! 

I did manage to upgrade my Phonegap from 3.3.x to 3.4.0-0.19.7. 
I'm on Fedora Core 20 
Android SDK Tools Revision 22.3.0
[gettarget] Project Target:   Android 4.4
[gettarget] API level:        19

Run the APK on my Nexus5. But, still, no working back-button.

Can you share your APK?

**Comment by sabre1041** [comment] 2014-03-06 14:44
Can you confirm a few things with your workspace. Can you remove the contents of the plugins and platforms directory and run `phonegap run android` which will attempt to add the platform and in turn add the plugin (PhoneGap hook present in `.cordova/hooks/after_platform_add/osm_install_plugins.js`)

Verify the configurations have been added to the `android.json` file in the plugins folder similar to the following:

```
{
"prepare_queue": {
    "installed": [],
    "uninstalled": []
},
"config_munge": {
    "res/xml/config.xml": {
        "/*": {
            "<feature name=\"InAppBrowser\"><param name=\"android-package\" value=\"org.apache.cordova.inappbrowser.InAppBrowser\" /></feature>": 1
        }
    }
},
"installed_plugins": {
    "org.apache.cordova.inappbrowser": {
        "PACKAGE_NAME": "com.openshift"
    }
},
"dependent_plugins": {}
}
```

**Comment by ron-murhammer** [comment] 2014-03-06 22:48
Upgraded build.phonegap to use phonegap 3.3.0 and use inappbrowser plugin 0.2.3. Please retest the bug with the latest build: https://build.phonegap.com/apps/796801/share

**Comment by jyore** [comment] 2014-03-06 23:00
Downloaded apk from the link provided and it worked fine on my device

Samsung Galaxy S3

**Comment by sabre1041** [comment] 2014-03-06 23:10
Also confirmed as well on galaxy a3 here

**Comment by ron-murhammer** [comment] 2014-03-07 01:06
Good to hear. I'll submit a pull request (https://github.com/sabre1041/openshift-mobile/pull/58) with the changes so we can close this. Might want to open a new one with the splash page issues.

**Comment by sabre1041** [comment] 2014-03-07 04:58
Pull request (https://github.com/sabre1041/openshift-mobile/pull/59) aligns the version of the `inappbrowser` with the version being utilized in https://github.com/sabre1041/openshift-mobile/pull/58 which is known to work when assembled using PhoneGap Build. Would you be able to delete the contents of the plugins and platforms directories and execute `phonegap run android`

**Comment by sabre1041** [comment] 2014-03-22 01:30
Closing as the issue has been resolved

**Closed as completed by sabre1041** 2014-03-22 01:30 UTC
Labels: bug
